// SPDX-License-Identifier: LGPL-2.1-or-later
#pragma once

#include <string_view>

namespace nomos::rt {

// Minimal per-sample DSP interface consumed by faust_modulator.
//
// Implementations are generated by alembic (via the Faust compiler) and
// wrapped in faust_dsp_adapter<Dsp> before being handed to faust_modulator.
// The interface is deliberately free of Faust headers so that nomos-rt itself
// does not depend on a Faust installation.
//
// process() always advances by exactly one sample (one block at 375 Hz).
// Outputs are written to the caller-supplied pointer array; each pointer
// addresses a single float (the sample for that output channel).
class dsp_block {
public:
    virtual ~dsp_block() = default;

    // Initialise or re-initialise at the given sample rate.  Called once
    // after construction and again if tick_rate_hz changes.
    virtual void init(float sample_rate) = 0;

    // Number of output channels this block produces.
    virtual int num_outputs() const = 0;

    // Set a named parameter (maps to Faust hslider labels).
    virtual void set_param(std::string_view key, float value) = 0;

    // Advance by one sample.  outputs[i] points to a single float for channel i.
    // The caller guarantees at least num_outputs() valid pointers.
    virtual void process(float** outputs) = 0;
};

} // namespace nomos::rt
